version: 2
jobs:
  buildAlgoliaIndex:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # run indexing
      - run:
          name: run indexing
          command: bundle exec jekyll algolia

  buildDockerImage:
    machine: true
    steps:
      - checkout
      - run:
          name: Generating Jekyll Site
          command: docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/builder jekyll build
      - run:
          name: Building Docker Image
          command: docker build -t elasticio/docs:${CIRCLE_SHA1} .

workflows:
  version: 2
  build:
    jobs:
      - buildDockerImage:
          filters:
            branches:
              only:
                - /stage_.+/
                - dockerizing_docs
      - buildAlgoliaIndex:
          filters:
            branches:
              only:
                - master
