version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
       - image: circleci/ruby:2.6.0-stretch-node
         environment:
           BUNDLER_VERSION: 2.0.2
           gem install bundler

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # run indexing
      - run:
          name: run indexing
          command: bundle exec jekyll algolia
